// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnFXIZAXsqpsY_kmv2nTo5vHgHNcuZ-k',
    appId: '1:932846129523:android:99c4bd52d6086bee93f506',
    messagingSenderId: '932846129523',
    projectId: 'haruchip-6a5aa',
    storageBucket: 'haruchip-6a5aa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4GFccTv_R1H5HuMj5I7AhS3DgsXoRUbQ',
    appId: '1:932846129523:ios:ebc2c60e813be8e993f506',
    messagingSenderId: '932846129523',
    projectId: 'haruchip-6a5aa',
    storageBucket: 'haruchip-6a5aa.firebasestorage.app',
    iosClientId: '932846129523-ltb00kpjgot5s78a9n43iar45mt50ove.apps.googleusercontent.com',
    iosBundleId: 'com.example.haruchip',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Ayr-F2qNMfauTEsSDpy7ykzeQlQiUcA',
    appId: '1:932846129523:web:dd25c0173dc0e7c193f506',
    messagingSenderId: '932846129523',
    projectId: 'haruchip-6a5aa',
    authDomain: 'haruchip-6a5aa.firebaseapp.com',
    storageBucket: 'haruchip-6a5aa.firebasestorage.app',
    measurementId: 'G-2E45MTKVR9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4GFccTv_R1H5HuMj5I7AhS3DgsXoRUbQ',
    appId: '1:932846129523:ios:ebc2c60e813be8e993f506',
    messagingSenderId: '932846129523',
    projectId: 'haruchip-6a5aa',
    storageBucket: 'haruchip-6a5aa.firebasestorage.app',
    iosClientId: '932846129523-ltb00kpjgot5s78a9n43iar45mt50ove.apps.googleusercontent.com',
    iosBundleId: 'com.example.haruchip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Ayr-F2qNMfauTEsSDpy7ykzeQlQiUcA',
    appId: '1:932846129523:web:678818f438abb1a493f506',
    messagingSenderId: '932846129523',
    projectId: 'haruchip-6a5aa',
    authDomain: 'haruchip-6a5aa.firebaseapp.com',
    storageBucket: 'haruchip-6a5aa.firebasestorage.app',
    measurementId: 'G-GJHER1EBKB',
  );
}
